name: Simple Python Workflow


on:
  workflow_dispatch:
    inputs:
      value:
        description: "Enter a or b"
        required: true
        type: choice
        options:
          - a
          - b

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Run Python inline
        run: |
          python - <<EOF
          import sys

          value = "${{ github.event.inputs.value }}"

          if value == "a":
              print("1")
          elif value == "b":
              print("error")
          else:
              print("unknown")
          EOF
