name: Input Example

on:
  workflow_dispatch:
    inputs:
      value:
        description: "Enter a or b"
        required: true
        type: choice
        options:
          - create-replica
          - create-local-repo
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: create-replica
        if: ${{ github.event.inputs.value == 'create-replica' }}
        run: echo "create-replica  and other stuff"

      - name: create-local-repo
        if: ${{ github.event.inputs.value == 'create-local-repo' }}
        run: echo "create-local-repo and other stuff"

